image: gitpod/workspace-dotnet

tasks:
  - before: cd KataUnitTest
    init: dotnet restore && dotnet build --configuration Debug --no-restore
    command: dotnet watch --project . test

vscode:
  extensions:
    - muhammad-sammy.csharp